language: node_js
node_js:
  - 6.9.5
os: linux
dist: xenial
sudo: required
compiler: gcc
env:
- MXE_TARGET=i686-w64-mingw32.static
install:
- echo "deb http://pkg.mxe.cc/repos/apt/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mxeapt.list
- sudo apt-key adv --keyserver x-hkp://keys.gnupg.net --recv-keys D43A795B73B16ABE9643FE1AFD8FFF16DB45C6AB
- sudo apt-get update
- sudo apt-get --yes install mxe-$MXE_TARGET-jsoncpp mxe-$MXE_TARGET-qtbase mxe-$MXE_TARGET-boost ninja-build
script:
- npm install
- patch -p1 < ./wrtc.patch
- npm run bundle
- wget https://github.com/FAForever/ice-adapter/releases/download/v5.0.0/wrtc.node -O ./dist/wrtc.node
- wget https://nodejs.org/dist/v6.9.5/win-x64/node.exe -O ./dist/node.exe
- export MXE_DIR=/usr/lib/mxe
- "$MXE_DIR/usr/bin/$MXE_TARGET-cmake --version"
- mkdir build && cd build
- "$MXE_DIR/usr/bin/$MXE_TARGET-cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=\"-march=i686\" -G \"Ninja\" ../testclient"
- ninja faf-ice-testclient
- cd ..
- cp ./build/faf-ice-testclient.exe ./dist/faf-ice-testclient.exe
- mv ./dist ./faf-ice-adapter
- zip -r faf-ice-adapter.zip ./faf-ice-adapter
deploy:
  provider: releases
  api_key:
    secure: dXe34Fx7IZJHnCDr1POgDI2Klm+R+PSh/r7oPFZwAN3A2Rgwmj5zLD3EeFIOUNqsB2ROtqzInhRAuHvPsEauPqSk2cgoWNQA3BpemgiXvaVGsMXsEFl05bURcC1ViWsI0DNGJSyLGlWphXV1LmqBXMcbUwv2dv4hVBU3ZR3FYVtd2dYgq1Ee3FRy1ZjTbTF495F4kEtYbQYYaq8jpW+cn5LTATu0enRZ/TC4b9AmgoTMYcjarw8DOZW59jogHFJYoTAdjklhyzpDdhuFS7ASkedX/ZsGYKbl9cllHBPo8hjxLGtLWbclHN2qob6n7QT4oa6k7pEnw2/TCjglKB4cuG0vhmtexNKFD4UMLdqxIqaSj2tsIyopXSf/qjwq9PMdxlY3Po+v1I/BdcT6U4c14wDpUE+ouyO5yhTF3zDJidJNnu8B0BgbVENuvax06Mw6/ho7Tt8YUANQ6h0RrrU71TBmG430S2hdOct2Fu9HNs+9zPGyX97lGPEVkYflaAtN83//oWijdxvh52UsRYdyu9n6rTdOr6CCeNY2TH7qe0kVTGZECCSW4fZ+/gNkFk5Xg2kx4R+jm0PsYEaFLVzZsWR0RnbJVFYZiBiWPABKAA3DtesRdL0DPI6VkvJx1bKJ9Ltwtu7fH6CVAQrHaL0gI7Bsk5t6ZwMONMBO8uAgOuA=
  file:
    - "./faf-ice-adapter/faf-ice-adapter.js"
    - "./faf-ice-adapter.zip"
  skip_cleanup: true
  on:
    tags: true
