language: node_js
node_js:
  - "6"
os: linux
dist: trusty
script:
# Compile the bundled ice-adapter
- npm install
- patch -p1 < ./wrtc.patch
- npm run bundle
# Create the windows release
- wget https://github.com/FAForever/node-webrtc/releases/download/v0.0.61-faf4/node-webrtc-win32.zip
- unzip node-webrtc-win32.zip
- cp -r ./dist ./faf-ice-adapter
- cp -r ./node-webrtc/* ./faf-ice-adapter
- zip -r faf-ice-adapter-win32-$TRAVIS_TAG.zip ./faf-ice-adapter
- rm ./faf-ice-adapter/wrtc.node
- rm ./faf-ice-adapter/node.exe
# Create the Linux release
- wget https://github.com/FAForever/node-webrtc/releases/download/v0.0.61-faf4/wrtc-linux64.node -O ./faf-ice-adapter/wrtc.node
- tar cfJ faf-ice-adapter-linux64-$TRAVIS_TAG.tar.xz faf-ice-adapter/
deploy:
  provider: releases
  api_key:
    secure: dXe34Fx7IZJHnCDr1POgDI2Klm+R+PSh/r7oPFZwAN3A2Rgwmj5zLD3EeFIOUNqsB2ROtqzInhRAuHvPsEauPqSk2cgoWNQA3BpemgiXvaVGsMXsEFl05bURcC1ViWsI0DNGJSyLGlWphXV1LmqBXMcbUwv2dv4hVBU3ZR3FYVtd2dYgq1Ee3FRy1ZjTbTF495F4kEtYbQYYaq8jpW+cn5LTATu0enRZ/TC4b9AmgoTMYcjarw8DOZW59jogHFJYoTAdjklhyzpDdhuFS7ASkedX/ZsGYKbl9cllHBPo8hjxLGtLWbclHN2qob6n7QT4oa6k7pEnw2/TCjglKB4cuG0vhmtexNKFD4UMLdqxIqaSj2tsIyopXSf/qjwq9PMdxlY3Po+v1I/BdcT6U4c14wDpUE+ouyO5yhTF3zDJidJNnu8B0BgbVENuvax06Mw6/ho7Tt8YUANQ6h0RrrU71TBmG430S2hdOct2Fu9HNs+9zPGyX97lGPEVkYflaAtN83//oWijdxvh52UsRYdyu9n6rTdOr6CCeNY2TH7qe0kVTGZECCSW4fZ+/gNkFk5Xg2kx4R+jm0PsYEaFLVzZsWR0RnbJVFYZiBiWPABKAA3DtesRdL0DPI6VkvJx1bKJ9Ltwtu7fH6CVAQrHaL0gI7Bsk5t6ZwMONMBO8uAgOuA=
  file_glob: true
  file:
    - "./dist/faf-ice-adapter.js"
    - "./faf-ice-adapter*.zip"
    - "./faf-ice-adapter*.tar.xz"
  skip_cleanup: true
  on:
    tags: true
